FROM node:14
ENV NPM_CONFIG_LOGLEVEL warn
ENV CHOKIDAR_USEPOLLING=true
ENV SKIP_PREFLIGHT_CHECK=true
ENV IS_PRODUCTION=false

# create frontend app dir
RUN mkdir -p /frontend
WORKDIR /frontend

# install deps
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile
# COPY package*.json ./
# RUN npm ci

# Bundle app source
COPY ./public ./public
COPY ./src/*.env ./src/

CMD if [ ${APP_ENV} = production ]; \
    then \
    yarn install --frozen-lockfile -g http-server && \
    yarn build && \
    cd build && \
    hs -p 3000; \
    else \
    yarn start; \
    fi

EXPOSE 3000
