import { users1, usersRecConnections, org } from './queryUsersById';

export const postsObj = {
  "fs98ufd9": {
    "_id": `34s343s`,
    "profileId": 'sd8x',
    "profile": { ...usersRecConnections['sd8x']},
    "body": "Mark your calendar for an April 26th, 2021 subordinate debt offering \n on a 376 MwH wind project development in southern Virginia. \n The minimum investment level is $15,000.",
    "postType": "interest",
    "dtCreated": 1619791196043,
  },
  "34s343s": {
    "_id": `34s343s`,
    "profileId": 'zxcv87',
    "profile": {...org['zxcv87']},
    "body": "Mark your calendar for an April 26th, 2021 subordinate debt offering on a 376 MwH wind project development in southern Virginia. The minimum investment level is $15,000. #SubDebtOffering",
    "postType": "offering",
    "dtCreated": 1619791296043,
  },
  "fvs9876": {
    "_id": `fvs9876`,
    "profileId": 'xcjij0',
    "profile": {...users1['xcjij0']},
    "body": "NOW LIVE: The La Rosa Battery Station preferred equity offering is now accepting capital commitments. Brookfield Renewables is providing this $34 million offer on a first-come-first-serve basis.\n 11% Expected Annual Returns = ✅ \n $120M Net Present Value = ✅ \n 340 MwH / per day =  ✅",
    "postType": "interest",
    "dtCreated": 1619791396043,
  },
  "s0987cxlvkn": {
    "_id": 's0987cxlvkn',
    "profileId": 's0987cxlvkn',
    "profile": {...org['s0987cxlvkn']},
    "body": "Wind Grid Capital Senior Vice President @Adam Stanley will be holding a zoom conference at 11:30 am EST on Thursday with investors in the Gold Tier Infrastructure Fund to go over FY 2021 projections.  #JoinUs",
    "postType": "rsvp",
    "dtCreated": 1619791496043,
  },
  "xcv0x9": {
    "_id": 'xcv0x9',
    "profileId": '3',
    "profile": {...users1['3']},
    "body": "Hello world. This is a test post you can like.",
    "postType": "social",
    "dtCreated": 1619771596043,
  },
  "vx09xv89v": {
    "_id": 'vx09xv89v',
    "profileId": '3',
    "profile": {...users1['3']},
    "body": "Why are building renovations so costly?  Typically the grid will be emissions-free by the time they're already done!! It may be wiser to reallocate the $$$ to speed up converting to electric + new effic. buildings near pub. transport https://test.link.here #innovate #renovate",
    "postType": "social",
    "dtCreated": 1619791596043,
  },
  "xcvxcvb": {
    "_id": 'xcvxcvb',
    "profileId": '3',
    "profile": {...users1['3']},
    "body": "Idea: Identifying the best underground sites for carbon sinks can take up to or even over 10 yrs.  We really need to start now.  There's no excuse to delay and theres an abundance of available sites near high emission regions. Storage is relatively cheap, but capture isnt: $20 per ton https://another.test.link.here #USA #Europe",
    "postType": "social",
    "dtCreated": 1619801596043,
  },
};