// main
export const UPDATE_LOGIN_STATUS = `UPDATE_LOGIN_STATUS`;
export const LOGOUT = `LOGOUT`;
export const UPDATE_PASSWORD = `UPDATE_PASSWORD`;
export const UPDATE_USERNAME = `UPDATE_USERNAME`;
export const UPDATE_LOGIN_FIELD = `UPDATE_LOGIN_FIELD`;
export const RESET_LOGIN_FORM = `RESET_LOGIN_FORM`;
export const LOGIN_UPDATE_FORM_FIELD_VALUE = `LOGIN_UPDATE_FORM_FIELD_VALUE`;
export const LOGIN_CHECK_IF_VALID_FORM = `LOGIN_CHECK_IF_VALID_FORM`;
// profile
export const RESET_PROFILE_FORM = 'RESET_PROFILE_FORM';
