export const OFFERING_UPDATE_FORM_VALID = 'OFFERING_UPDATE_FORM_VALID';
export const OFFERING_UPDATE_FORM_FIELD_VALUE = 'OFFERING_UPDATE_FORM_FIELD_VALUE';
export const OFFERING_UPDATE_FORM_FIELD_ERROR = 'OFFERING_UPDATE_FORM_FIELD_ERROR';
export const OFFERING_UPDATE_ACTIVE_FORM = 'OFFERING_UPDATE_ACTIVE_FORM';
export const OFFERING_UPDATE_FORM_FIELD = 'OFFERING_UPDATE_FORM_FIELD';
export const OFFERING_CHECK_IF_VALID_FORM = 'OFFERING_CHECK_IF_VALID_FORM';
export const OFFERING_CHECK_IF_ALL_VALID_FORMS = 'OFFERING_CHECK_IF_ALL_VALID_FORMS';
export const OFFERING_RESET_ALL_FORMS = 'OFFERING_RESET_ALL_FORMS';
