export const RSVP_UPDATE_FORM_VALID = 'RSVP_UPDATE_FORM_VALID';
export const RSVP_UPDATE_FORM_FIELD_VALUE = 'RSVP_UPDATE_FORM_FIELD_VALUE';
export const RSVP_UPDATE_FORM_FIELD_ERROR = 'RSVP_UPDATE_FORM_FIELD_ERROR';
export const RSVP_UPDATE_ACTIVE_FORM = 'RSVP_UPDATE_ACTIVE_FORM';
export const RSVP_UPDATE_FORM_FIELD = 'RSVP_UPDATE_FORM_FIELD';
export const RSVP_CHECK_IF_VALID_FORM = 'RSVP_CHECK_IF_VALID_FORM';
export const RSVP_CHECK_IF_ALL_VALID_FORMS = 'RSVP_CHECK_IF_ALL_VALID_FORMS';
export const RSVP_RESET_ALL_FORMS = 'RSVP_RESET_ALL_FORMS';
