export const F_FP_LOAD_INIT_STATE = 'F_FP_LOAD_INIT_STATE';
export const F_FP_UPDATE_FORM_FIELD_VALUE = 'F_FP_UPDATE_FORM_FIELD_VALUE';
export const F_FP_UPDATE_FORM_FIELD_ERROR = 'F_FP_UPDATE_FORM_FIELD_ERROR';
export const F_FP_CHECK_IF_VALID_FORM = 'F_FP_CHECK_IF_VALID_FORM';
export const F_FP_CHECK_IF_ALL_VALID_FORMS = 'F_FP_CHECK_IF_ALL_VALID_FORMS';
export const F_FP_RESET_ALL_FORMS = 'F_FP_RESET_ALL_FORMS';
export const F_FP_CLEAR_FORM = 'F_FP_CLEAR_FORM';
