export const UPDATE_PROFILE_FORM = 'UPDATE_PROFILE_FORM';
export const UPDATE_FORM_VALID = 'UPDATE_FORM_VALID';
export const UPDATE_FORM_FIELD_VALUE = 'UPDATE_FORM_FIELD_VALUE';
export const UPDATE_FORM_FIELD_ERROR = 'UPDATE_FORM_FIELD_ERROR';
export const UPDATE_ACTIVE_FORM = 'UPDATE_ACTIVE_FORM';
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const CHECK_IF_VALID_FORM = 'CHECK_IF_VALID_FORM';
export const CHECK_IF_ALL_VALID_FORMS = 'CHECK_IF_ALL_VALID_FORMS';
