export const UPDATE_VIEW = 'UPDATE_VIEW';
export const IS_DARK_MODE = 'IS_DARK_MODE';
export const UPDATE_L1 = 'UPDATE_L1';
// profile
export const UPDATE_PROFILE_TAB = 'UPDATE_PROFILE_TAB';
export const UPDATE_VIEW_PROFILE = 'UPDATE_VIEW_PROFILE';
export const CLEAR_VIEW_PROFILE = 'CLEAR_VIEW_PROFILE';
export const UPDATE_RECOMMENDED_CONNECTIONS = 'UPDATE_RECOMMENDED_CONNECTIONS';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const UPDATE_PROFILE_POSTS = 'UPDATE_PROFILE_POSTS';
export const UPDATE_LIKED_ITEMS = 'UPDATE_LIKED_ITEMS';
// messages
export const MSG_UPDATE_ACTIVE_CONVERSATION_IDX = 'MSG_UPDATE_ACTIVE_CONVERSATION_IDX';
export const MSG_UPDATE_ACTIVE_CONVERSATION_ID = 'MSG_UPDATE_ACTIVE_CONVERSATION_ID';
export const MSG_UPDATE_ACTIVE_CONVERSATION = 'MSG_UPDATE_ACTIVE_CONVERSATION';
export const MSG_UPDATE_ACTIVE_CONVERSATION_OBJ = 'MSG_UPDATE_ACTIVE_CONVERSATION_OBJ';
export const MSG_UPDATE_PROFILE_MAP = 'MSG_UPDATE_PROFILE_MAP';
export const MSG_UPDATE_CONVERSATIONS_ARR = 'MSG_UPDATE_CONVERSATIONS_ARR';
// feed
export const UPDATE_POSTS_ARR = 'UPDATE_POSTS_ARR';
export const UPDATE_POSTS_OBJ = 'UPDATE_POSTS_OBJ';
export const UPDATE_POST_LIKES = 'UPDATE_POST_LIKES';
export const UPDATE_POST_REPOSTS = 'UPDATE_POST_REPOSTS';
export const UPDATE_POST_COMMENTS = 'UPDATE_POST_COMMENTS';
export const CLEAR_FEED = 'CLEAR_FEED';
// startup
export const UPDATE_STARTUPS_ARR = 'UPDATE_STARTUPS_ARR';
export const UPDATE_ACTIVE_STARTUP_OBJ = 'UPDATE_ACTIVE_STARTUP_OBJ';
export const UPDATE_ACTIVE_STARTUP_OBJ_FIELD = 'UPDATE_ACTIVE_STARTUP_OBJ_FIELD';
export const UPDATE_STARTUP_REPOSTS = 'UPDATE_STARTUP_REPOSTS';
export const UPDATE_STARTUP_LIKES = 'UPDATE_STARTUP_LIKES';
export const CLEAR_ACTIVE_STARTUP = 'CLEAR_ACTIVE_STARTUP';
// search
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
// post detail
export const OVERWRITE_POST_DETAIL = 'OVERWRITE_POST_DETAIL';
export const CLEAR_POST_DETAIL = 'CLEAR_POST_DETAIL';
