export const UPDATE_VIEW = 'UPDATE_VIEW';
export const IS_DARK_MODE = 'IS_DARK_MODE';
export const UPDATE_L1 = 'UPDATE_L1';
// profile
export const UPDATE_PROFILE_TAB = 'UPDATE_PROFILE_TAB';
export const UPDATE_VIEW_PROFILE = 'UPDATE_VIEW_PROFILE';
// messages
export const UPDATE_ACTIVE_CONVERSATION_IDX = 'UPDATE_ACTIVE_CONVERSATION_IDX';
export const UPDATE_ACTIVE_CONVERSATION_ID = 'UPDATE_ACTIVE_CONVERSATION_ID';
export const UPDATE_ACTIVE_CONVERSATION = 'UPDATE_ACTIVE_CONVERSATION';
export const UPDATE_ACTIVE_CONVERSATION_OBJ = 'UPDATE_ACTIVE_CONVERSATION_OBJ';
export const UPDATE_PROFILE_MAP = 'UPDATE_PROFILE_MAP';
// feed
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const CLEAR_FEED = 'CLEAR_FEED';
