export const UPDATE_VIEW = 'UPDATE_VIEW';
export const IS_DARK_MODE = 'IS_DARK_MODE';
export const UPDATE_L1 = 'UPDATE_L1';
// profile
export const UPDATE_PROFILE_TAB = 'UPDATE_PROFILE_TAB';
export const UPDATE_VIEW_PROFILE = 'UPDATE_VIEW_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
// messages
export const UPDATE_ACTIVE_CONVERSATION_IDX = 'UPDATE_ACTIVE_CONVERSATION_IDX';
export const UPDATE_ACTIVE_CONVERSATION_ID = 'UPDATE_ACTIVE_CONVERSATION_ID';
export const UPDATE_ACTIVE_CONVERSATION = 'UPDATE_ACTIVE_CONVERSATION';
export const UPDATE_ACTIVE_CONVERSATION_OBJ = 'UPDATE_ACTIVE_CONVERSATION_OBJ';
export const UPDATE_PROFILE_MAP = 'UPDATE_PROFILE_MAP';
// feed
export const UPDATE_POSTS_ARR = 'UPDATE_POSTS_ARR';
export const UPDATE_POSTS_OBJ = 'UPDATE_POSTS_OBJ';
export const UPDATE_POST_LIKES = 'UPDATE_POST_LIKES';
export const UPDATE_POST_COMMENTS = 'UPDATE_POST_COMMENTS';
export const CLEAR_FEED = 'CLEAR_FEED';
// startup
export const UPDATE_STARTUPS_ARR = 'UPDATE_STARTUPS_ARR';
export const UPDATE_ACTIVE_STARTUP_OBJ = 'UPDATE_ACTIVE_STARTUP_OBJ';
export const UPDATE_ACTIVE_STARTUP_OBJ_FIELD = 'UPDATE_ACTIVE_STARTUP_OBJ_FIELD';
export const UPDATE_STARTUP_REPOSTS = 'UPDATE_STARTUP_REPOSTS';
export const UPDATE_STARTUP_LIKES = 'UPDATE_STARTUP_LIKES';
export const CLEAR_ACTIVE_STARTUP = 'CLEAR_ACTIVE_STARTUP';
// search
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
